const BOOKS = [
 {
  "title": "Computer Networking: A Top-Down Approach",
  "author": "Kurose & Ross",
  "publisher": "Pearson India",
  "qty": 3.0,
  "amount": 999.0,
  "subject": "Computer Networks",
  "subjectCode": "BTCO13401",
  "semester": 4,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Computer Networks, 5th Edn.",
  "author": "Andrew S. Tanenbaum & David Wetherall",
  "publisher": "Pearson India",
  "qty": 3.0,
  "amount": 759.0,
  "subject": "Computer Networks",
  "subjectCode": "BTCO13401",
  "semester": 4,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Data Communications and Networking, 5th Edn.",
  "author": "Behrouz A. Forouzan",
  "publisher": "McGraw Hill India",
  "qty": 3.0,
  "amount": 599.0,
  "subject": "Computer Networks",
  "subjectCode": "BTCO13401",
  "semester": 4,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "An Introduction to Database Systems, 8th Edn.",
  "author": "C. J. Date",
  "publisher": "Pearson India",
  "qty": 3.0,
  "amount": 1230.0,
  "subject": "Database Management Systems",
  "subjectCode": "BTCO13404",
  "semester": 4,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Database System Concepts, 7th Edn.",
  "author": "Silberschatz, Korth & Sudarshan",
  "publisher": "McGraw-Hill India",
  "qty": 3.0,
  "amount": 1099.0,
  "subject": "Database Management Systems",
  "subjectCode": "BTCO13404",
  "semester": 4,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Fundamentals of Database Systems, 7th Edn.",
  "author": "Elmasri & Navathe",
  "publisher": "Pearson India",
  "qty": 3.0,
  "amount": 925.0,
  "subject": "Database Management Systems",
  "subjectCode": "BTCO13404",
  "semester": 4,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "SQL, PL/SQL: The Programming Language of Oracle, 4th Rev. Edn.",
  "author": "Ivan Bayross",
  "publisher": "BPB Publications",
  "qty": 3.0,
  "amount": 475.0,
  "subject": "Database Management Systems",
  "subjectCode": "BTCO13404",
  "semester": 4,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Fundamentals of Algorithmics",
  "author": "Gilles Brassard & Paul Bratley",
  "publisher": "Pearson India",
  "qty": 3.0,
  "amount": 649.0,
  "subject": "Design & Analysis of Algorithms",
  "subjectCode": "BTCO13403",
  "semester": 4,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Fundamentals of Computer Algorithms, 2nd Edn.",
  "author": "Horowitz, Sahni & Rajasekaran",
  "publisher": "Universities Press",
  "qty": 3.0,
  "amount": 995.0,
  "subject": "Design & Analysis of Algorithms",
  "subjectCode": "BTCO13403",
  "semester": 4,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Introduction to Algorithms, 3rd Edn.",
  "author": "Cormen, Leiserson, Rivest & Stein",
  "publisher": "PHI Learning",
  "qty": 3.0,
  "amount": 995.0,
  "subject": "Design & Analysis of Algorithms",
  "subjectCode": "BTCO13403",
  "semester": 4,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Modern Operating Systems, 5th Edn.",
  "author": "Andrew S. Tanenbaum",
  "publisher": "Pearson India",
  "qty": 3.0,
  "amount": 870.0,
  "subject": "Operating Systems",
  "subjectCode": "BTCO13402",
  "semester": 4,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Operating System Concepts, 10th Edn.",
  "author": "Silberschatz, Galvin & Gagne",
  "publisher": "Wiley India",
  "qty": 3.0,
  "amount": 999.0,
  "subject": "Operating Systems",
  "subjectCode": "BTCO13402",
  "semester": 4,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Operating Systems: Internals and Design Principles, 9th Edn.",
  "author": "William Stallings",
  "publisher": "Pearson India",
  "qty": 3.0,
  "amount": 900.0,
  "subject": "Operating Systems",
  "subjectCode": "BTCO13402",
  "semester": 4,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "UNIX Concepts and Applications, 4th Edn.",
  "author": "Sumitabha Das",
  "publisher": "McGraw Hill India",
  "qty": 3.0,
  "amount": 675.0,
  "subject": "Operating Systems",
  "subjectCode": "BTCO13402",
  "semester": 4,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "UNIX Shell Programming",
  "author": "Yashwant Kanetkar",
  "publisher": "BPB Publications",
  "qty": 3.0,
  "amount": 300.0,
  "subject": "Operating Systems",
  "subjectCode": "BTCO13402",
  "semester": 4,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "An Introduction to Genetic Algorithms",
  "author": "Melanie Mitchell",
  "publisher": "MIT Press (Import)",
  "qty": 3.0,
  "amount": 3000.0,
  "subject": "Bio-Inspired Computing",
  "subjectCode": "BTAI14501",
  "semester": 5,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Ant Colony Optimization",
  "author": "Marco Dorigo & Thomas Stutzle",
  "publisher": "MIT Press (Import)",
  "qty": 3.0,
  "amount": 3500.0,
  "subject": "Bio-Inspired Computing",
  "subjectCode": "BTAI14501",
  "semester": 5,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Nature-Inspired Optimization Algorithms",
  "author": "Xin-She Yang",
  "publisher": "Elsevier (Import)",
  "qty": 3.0,
  "amount": 7000.0,
  "subject": "Bio-Inspired Computing",
  "subjectCode": "BTAI14501",
  "semester": 5,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Particle Swarm Optimization",
  "author": "Adam Slowik",
  "publisher": "CRC Press (Import)",
  "qty": 3.0,
  "amount": 5500.0,
  "subject": "Bio-Inspired Computing",
  "subjectCode": "BTAI14501",
  "semester": 5,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Soft Computing",
  "author": "Samir Roy & Udit Chakraborty",
  "publisher": "Pearson India",
  "qty": 3.0,
  "amount": 650.0,
  "subject": "Bio-Inspired Computing",
  "subjectCode": "BTAI14501",
  "semester": 5,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Cloud Computing - A Practical Approach",
  "author": "Velte, Velte & Elsenpeter",
  "publisher": "Tata McGraw-Hill",
  "qty": 3.0,
  "amount": 650.0,
  "subject": "Cloud Computing",
  "subjectCode": "BTIT14502",
  "semester": 5,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Cloud Computing Bible",
  "author": "Barrie Sosinsky",
  "publisher": "Wiley India",
  "qty": 3.0,
  "amount": 650.0,
  "subject": "Cloud Computing",
  "subjectCode": "BTIT14502",
  "semester": 5,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Cloud Computing: Principles and Paradigms",
  "author": "Rajkumar Buyya",
  "publisher": "Wiley India",
  "qty": 3.0,
  "amount": 750.0,
  "subject": "Cloud Computing",
  "subjectCode": "BTIT14502",
  "semester": 5,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Cloud Security: A Comprehensive Guide to Secure Cloud Computing",
  "author": "Ronald L. Krutz & Russell Dean Vines",
  "publisher": "Wiley (Import)",
  "qty": 3.0,
  "amount": 3000.0,
  "subject": "Cloud Computing",
  "subjectCode": "BTIT14502",
  "semester": 5,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Cyber-Physical Systems",
  "author": "Raj Rajkumar, Dionisio de Niz & Mark Klein",
  "publisher": "Addison-Wesley (Import)",
  "qty": 3.0,
  "amount": 4500.0,
  "subject": "Cyber Physical Systems",
  "subjectCode": "BTIT14503",
  "semester": 5,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Cyber-Physical Systems",
  "author": "Fei Hu",
  "publisher": "CRC Press (Import)",
  "qty": 3.0,
  "amount": 5500.0,
  "subject": "Cyber Physical Systems",
  "subjectCode": "BTIT14503",
  "semester": 5,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Introduction to Embedded Systems: A Cyber-Physical Systems Approach",
  "author": "E. A. Lee & S. A. Seshia",
  "publisher": "MIT Press (Import)",
  "qty": 3.0,
  "amount": 3500.0,
  "subject": "Cyber Physical Systems",
  "subjectCode": "BTIT14503",
  "semester": 5,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Principles of Cyber-Physical Systems",
  "author": "R. Alur",
  "publisher": "MIT Press (Import)",
  "qty": 3.0,
  "amount": 3500.0,
  "subject": "Cyber Physical Systems",
  "subjectCode": "BTIT14503",
  "semester": 5,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Data Mining for Business Applications",
  "author": "Longbing Cao, Philip S. Yu, Chengqi Zhang, Huaifeng Zhang",
  "publisher": "Springer (Import)",
  "qty": 3.0,
  "amount": 5000.0,
  "subject": "Data Mining and Business Intelligence",
  "subjectCode": "BTIT13501",
  "semester": 5,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Data Mining for Business Intelligence",
  "author": "Shmueli, Bruce, Yahav, Patel, Lichtendahl Jr.",
  "publisher": "Wiley (Import)",
  "qty": 3.0,
  "amount": 2000.0,
  "subject": "Data Mining and Business Intelligence",
  "subjectCode": "BTIT13501",
  "semester": 5,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Data Mining: Concepts and Techniques",
  "author": "J. Han & M. Kamber",
  "publisher": "Morgan Kaufmann/Elsevier (Import)",
  "qty": 3.0,
  "amount": 2200.0,
  "subject": "Data Mining and Business Intelligence",
  "subjectCode": "BTIT13501",
  "semester": 5,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Data Mining: Introductory and Advanced Topics",
  "author": "M. Dunham",
  "publisher": "Pearson Education",
  "qty": 3.0,
  "amount": 850.0,
  "subject": "Data Mining and Business Intelligence",
  "subjectCode": "BTIT13501",
  "semester": 5,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Data Science for Dummies",
  "author": "John Muller",
  "publisher": "Wiley (Import)",
  "qty": 3.0,
  "amount": 1600.0,
  "subject": "Fundamentals of Data Science",
  "subjectCode": "BTAI13502",
  "semester": 5,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Practical Statistics for Data Scientists, 2nd Edn.",
  "author": "Peter Bruce & Andrew Bruce",
  "publisher": "Shroff/O'Reilly",
  "qty": 3.0,
  "amount": 1300.0,
  "subject": "Fundamentals of Data Science",
  "subjectCode": "BTAI13502",
  "semester": 5,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Statistics for Data Science",
  "author": "James D. Miller",
  "publisher": "PACKT (Import)",
  "qty": 3.0,
  "amount": 2800.0,
  "subject": "Fundamentals of Data Science",
  "subjectCode": "BTAI13502",
  "semester": 5,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Think Stats: Probability and Statistics for Programmers",
  "author": "Allen B. Downey",
  "publisher": "Green Tea Press/O'Reilly (Import)",
  "qty": 3.0,
  "amount": 900.0,
  "subject": "Fundamentals of Data Science",
  "subjectCode": "BTAI13502",
  "semester": 5,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Core Java Volume-I Fundamentals",
  "author": "Cay S. Horstmann & Gray Cornell",
  "publisher": "Pearson Education",
  "qty": 3.0,
  "amount": 1200.0,
  "subject": "Programming with Java",
  "subjectCode": "BTIT15502",
  "semester": 5,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Introduction to Java Programming and Data Structures",
  "author": "Y. Daniel Liang",
  "publisher": "Pearson Education",
  "qty": 3.0,
  "amount": 950.0,
  "subject": "Programming with Java",
  "subjectCode": "BTIT15502",
  "semester": 5,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Java - The Complete Reference, 13th Edn.",
  "author": "Herbert Schildt",
  "publisher": "McGraw-Hill India",
  "qty": 3.0,
  "amount": 995.0,
  "subject": "Programming with Java",
  "subjectCode": "BTIT15502",
  "semester": 5,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Java Fundamentals",
  "author": "Herbert Schildt & Dale Skrien",
  "publisher": "McGraw-Hill India",
  "qty": 3.0,
  "amount": 995.0,
  "subject": "Programming with Java",
  "subjectCode": "BTIT15502",
  "semester": 5,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Artificial Intelligence, 3rd Edn.",
  "author": "Elaine Rich & Kevin Knight",
  "publisher": "McGraw-Hill India",
  "qty": 3.0,
  "amount": 850.0,
  "subject": "Search Algorithms in AI",
  "subjectCode": "BTAI13501",
  "semester": 5,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Artificial Intelligence: A Modern Approach, 4th Edn.",
  "author": "Stuart Russell & Peter Norvig",
  "publisher": "Pearson India",
  "qty": 3.0,
  "amount": 999.0,
  "subject": "Search Algorithms in AI",
  "subjectCode": "BTAI13501",
  "semester": 5,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Artificial Intelligence: A New Synthesis",
  "author": "Nils J. Nilsson",
  "publisher": "Morgan Kaufmann (Import)",
  "qty": 3.0,
  "amount": 5000.0,
  "subject": "Search Algorithms in AI",
  "subjectCode": "BTAI13501",
  "semester": 5,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "An Integrated Approach to Software Engineering",
  "author": "Pankaj Jalote",
  "publisher": "Narosa Publishing",
  "qty": 3.0,
  "amount": 450.0,
  "subject": "Software Engineering",
  "subjectCode": "BTIT14501",
  "semester": 5,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Fundamentals of Software Engineering",
  "author": "Rajib Mall",
  "publisher": "PHI Learning",
  "qty": 3.0,
  "amount": 450.0,
  "subject": "Software Engineering",
  "subjectCode": "BTIT14501",
  "semester": 5,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Software Engineering, 10th Edn.",
  "author": "Ian Sommerville",
  "publisher": "Pearson India",
  "qty": 3.0,
  "amount": 899.0,
  "subject": "Software Engineering",
  "subjectCode": "BTIT14501",
  "semester": 5,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Software Engineering: A Practitioner's Approach, 9th Edn.",
  "author": "Roger S. Pressman & Bruce Maxim",
  "publisher": "McGraw-Hill India",
  "qty": 3.0,
  "amount": 1025.0,
  "subject": "Software Engineering",
  "subjectCode": "BTIT14501",
  "semester": 5,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Artificial Intelligence, 3rd Edition",
  "author": "Elaine Rich, Kevin Knight & Shivashankar B. Nair",
  "publisher": "McGraw Hill Education India",
  "qty": 5.0,
  "amount": 850.0,
  "subject": "AI",
  "subjectCode": "BTIT15601",
  "semester": 6,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Artificial Intelligence: A Modern Approach, 3rd Edition",
  "author": "Stuart J. Russell & Peter Norvig",
  "publisher": "Pearson India",
  "qty": 5.0,
  "amount": 950.0,
  "subject": "AI",
  "subjectCode": "BTIT15601",
  "semester": 6,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Applied Machine Learning",
  "author": "Madan Gopal",
  "publisher": "McGraw Hill Education India",
  "qty": 3.0,
  "amount": 650.0,
  "subject": "Applied Machine Learning",
  "subjectCode": "BTAI13603",
  "semester": 6,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Introduction to Machine Learning",
  "author": "Ethem Alpaydin",
  "publisher": "PHI Learning",
  "qty": 3.0,
  "amount": 500.0,
  "subject": "Applied Machine Learning",
  "subjectCode": "BTAI13603",
  "semester": 6,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Pattern Classification",
  "author": "Richard O. Duda, Peter E. Hart, David G. Stork",
  "publisher": "Wiley India",
  "qty": 3.0,
  "amount": 750.0,
  "subject": "Applied Machine Learning",
  "subjectCode": "BTAI13603",
  "semester": 6,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Artificial Intelligence and Cybersecurity: Advances and Innovations",
  "author": "Ishaani Priyadarshini, Rohit Sharma",
  "publisher": "CRC Press",
  "qty": 3.0,
  "amount": 5000.0,
  "subject": "Artificial Intelligence for Cyber Security",
  "subjectCode": "BTAI14602",
  "semester": 6,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Artificial Intelligence, Cybersecurity and Cyber Defence",
  "author": "Daniel Ventre",
  "publisher": "Wiley-ISTE",
  "qty": 3.0,
  "amount": 6000.0,
  "subject": "Artificial Intelligence for Cyber Security",
  "subjectCode": "BTAI14602",
  "semester": 6,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Hands-On Artificial Intelligence for Cybersecurity",
  "author": "Alessandro Parisi",
  "publisher": "Packt Publishing",
  "qty": 3.0,
  "amount": 2800.0,
  "subject": "Artificial Intelligence for Cyber Security",
  "subjectCode": "BTAI14602",
  "semester": 6,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Big Data and Analytics",
  "author": "Seema Acharya, Subhashini Chhellappan",
  "publisher": "Wiley India",
  "qty": 3.0,
  "amount": 500.0,
  "subject": "Big Data Analytics",
  "subjectCode": "BTAI14601",
  "semester": 6,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Hadoop - The Definitive Guide",
  "author": "Tom White",
  "publisher": "O'Reilly / Shroff (India reprint)",
  "qty": 3.0,
  "amount": 800.0,
  "subject": "Big Data Analytics",
  "subjectCode": "BTAI14601",
  "semester": 6,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Learning Spark",
  "author": "Jules S. Damji, Brooke Wenig, Tathagata Das & Denny Lee",
  "publisher": "O'Reilly / Shroff (India reprint)",
  "qty": 3.0,
  "amount": 700.0,
  "subject": "Big Data Analytics",
  "subjectCode": "BTAI14601",
  "semester": 6,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Learning Spark: Lightning-Fast Big Data Analysis (1st Ed.)",
  "author": "Holden Karau, Andy Konwinski, Patrick Wendell & Matei Zaharia",
  "publisher": "O'Reilly (Import)",
  "qty": 3.0,
  "amount": 600.0,
  "subject": "Big Data Analytics",
  "subjectCode": "BTAI14601",
  "semester": 6,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Understanding Big Data",
  "author": "Chris Eaton, Dirk deRoos",
  "publisher": "McGraw Hill",
  "qty": 3.0,
  "amount": 600.0,
  "subject": "Big Data Analytics",
  "subjectCode": "BTAI14601",
  "semester": 6,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Data Compression: Methods and Theory",
  "author": "James A. Storer",
  "publisher": "Computer Science Press",
  "qty": 3.0,
  "amount": null,
  "subject": "Data Compression",
  "subjectCode": "BTIT14608",
  "semester": 6,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Data Compression: The Complete Reference",
  "author": "David Salomon",
  "publisher": "Springer",
  "qty": 3.0,
  "amount": 4800.0,
  "subject": "Data Compression",
  "subjectCode": "BTIT14608",
  "semester": 6,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Introduction to Data Compression",
  "author": "Khalid Sayood",
  "publisher": "Morgan Kaufmann / Elsevier India",
  "qty": 3.0,
  "amount": 1200.0,
  "subject": "Data Compression",
  "subjectCode": "BTIT14608",
  "semester": 6,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "The Data Compression Book",
  "author": "Mark Nelson",
  "publisher": "John Wiley & Sons",
  "qty": 3.0,
  "amount": null,
  "subject": "Data Compression",
  "subjectCode": "BTIT14608",
  "semester": 6,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Data Visualization Made Simple: Insights into Becoming Visual",
  "author": "Kristen Sosulski",
  "publisher": "Routledge",
  "qty": 3.0,
  "amount": 3736.0,
  "subject": "Data Visualization and Presentation",
  "subjectCode": "BTAI13601",
  "semester": 6,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Interactive Data Visualization for the Web",
  "author": "Scott Murray",
  "publisher": "O'Reilly Media / Shroff (India reprint)",
  "qty": 3.0,
  "amount": 650.0,
  "subject": "Data Visualization and Presentation",
  "subjectCode": "BTAI13601",
  "semester": 6,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "JavaScript and jQuery for Data Analysis and Visualization",
  "author": "Jon Raasch, Graham Murray, Vadim Ogievetsky, Joseph Lowery",
  "publisher": "John Wiley & Sons",
  "qty": 3.0,
  "amount": 1500.0,
  "subject": "Data Visualization and Presentation",
  "subjectCode": "BTAI13601",
  "semester": 6,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "ASP.NET Complete Reference",
  "author": "Matthew Macdonald and Robert Standefer",
  "publisher": "Tata McGraw-Hill",
  "qty": 3.0,
  "amount": null,
  "subject": "DotNet Technology",
  "subjectCode": "BTIT14606",
  "semester": 6,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "C# The Basics",
  "author": "Vijay Mukhi",
  "publisher": "BPB Publications",
  "qty": 3.0,
  "amount": 400.0,
  "subject": "DotNet Technology",
  "subjectCode": "BTIT14606",
  "semester": 6,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Professional C# .NET",
  "author": "Christian Nagel",
  "publisher": "Wrox / Wiley India",
  "qty": 3.0,
  "amount": 800.0,
  "subject": "DotNet Technology",
  "subjectCode": "BTIT14606",
  "semester": 6,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Hacking Exposed: Network Security Secrets and Solutions",
  "author": "Stuart McClure, Joel Scambray & George Kurtz",
  "publisher": "Tata McGraw-Hill",
  "qty": 5.0,
  "amount": 750.0,
  "subject": "Information Security",
  "subjectCode": "BTIT15602",
  "semester": 6,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Handbook of Information Security Management",
  "author": "Micki Krause & Harold F. Tipton",
  "publisher": "CRC Press LLC",
  "qty": 3.0,
  "amount": 3500.0,
  "subject": "Information Security",
  "subjectCode": "BTIT15602",
  "semester": 6,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Principles of Information Security, Latest Edition",
  "author": "Michael E. Whitman & Herbert J. Mattord",
  "publisher": "Cengage Learning India",
  "qty": 5.0,
  "amount": 900.0,
  "subject": "Information Security",
  "subjectCode": "BTIT15602",
  "semester": 6,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Artificial Intelligence",
  "author": "Elaine Rich, Kevin Knight & Shivashankar B. Nair",
  "publisher": "Tata McGraw-Hill",
  "qty": 3.0,
  "amount": 850.0,
  "subject": "Knowledge Representation and Reasoning",
  "subjectCode": "BTAI13602",
  "semester": 6,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Artificial Intelligence: A Modern Approach, 3rd Edition",
  "author": "Stuart J. Russell, Peter Norvig",
  "publisher": "Pearson India",
  "qty": 3.0,
  "amount": 950.0,
  "subject": "Knowledge Representation and Reasoning",
  "subjectCode": "BTAI13602",
  "semester": 6,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Introduction to Turbo PROLOG",
  "author": "Carl Townsend",
  "publisher": "BPB Publications",
  "qty": 3.0,
  "amount": null,
  "subject": "Knowledge Representation and Reasoning",
  "subjectCode": "BTAI13602",
  "semester": 6,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Knowledge Representation and Reasoning",
  "author": "Ron Brachman and Hector Levesque",
  "publisher": "Morgan Kaufmann (Elsevier)",
  "qty": 3.0,
  "amount": 4500.0,
  "subject": "Knowledge Representation and Reasoning",
  "subjectCode": "BTAI13602",
  "semester": 6,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "PROLOG Programming For Artificial Intelligence",
  "author": "Ivan Bratko",
  "publisher": "Addison-Wesley / Pearson",
  "qty": 3.0,
  "amount": 3500.0,
  "subject": "Knowledge Representation and Reasoning",
  "subjectCode": "BTAI13602",
  "semester": 6,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Android Application Development Black Book",
  "author": "Pradeep Kothari",
  "publisher": "DreamTech Press",
  "qty": 3.0,
  "amount": 550.0,
  "subject": "Mobile Application Development",
  "subjectCode": "BTIT14602",
  "semester": 6,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Android Wireless Application Development",
  "author": "Lauren Darcey, Shane Conder",
  "publisher": "Pearson India",
  "qty": 3.0,
  "amount": 650.0,
  "subject": "Mobile Application Development",
  "subjectCode": "BTIT14602",
  "semester": 6,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Beginning Android 4 Application Development",
  "author": "Wei-Meng Lee",
  "publisher": "Wrox / Wiley India",
  "qty": 3.0,
  "amount": 600.0,
  "subject": "Mobile Application Development",
  "subjectCode": "BTIT14602",
  "semester": 6,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "System Software",
  "author": "Chattopadhyay Santanu",
  "publisher": "PHI Learning",
  "qty": 3.0,
  "amount": 400.0,
  "subject": "System Programming",
  "subjectCode": "BTAI14603",
  "semester": 6,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Systems Programming",
  "author": "Pal Srimanta",
  "publisher": "Oxford University Press India",
  "qty": 3.0,
  "amount": 500.0,
  "subject": "System Programming",
  "subjectCode": "BTAI14603",
  "semester": 6,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Systems Programming",
  "author": "Dhananjay Dhamdhere",
  "publisher": "McGraw Hill Education",
  "qty": 3.0,
  "amount": 500.0,
  "subject": "System Programming",
  "subjectCode": "BTAI14603",
  "semester": 6,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Systems Programming",
  "author": "John Donovan",
  "publisher": "McGraw Hill Education",
  "qty": 3.0,
  "amount": null,
  "subject": "System Programming",
  "subjectCode": "BTAI14603",
  "semester": 6,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Data Mining: Concepts and Techniques",
  "author": "J. Han, M. Kamber, J. Pei",
  "publisher": "Morgan Kaufmann / Elsevier India",
  "qty": 3.0,
  "amount": 850.0,
  "subject": "Web Intelligence and Mining",
  "subjectCode": "BTAI14604",
  "semester": 6,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Mining the Web: Discovering Knowledge from Hypertext Data",
  "author": "Soumen Chakrabarti",
  "publisher": "Morgan Kaufmann",
  "qty": 3.0,
  "amount": 4500.0,
  "subject": "Web Intelligence and Mining",
  "subjectCode": "BTAI14604",
  "semester": 6,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Web Data Mining: Exploring Hyperlinks, Contents and Usage Data",
  "author": "Bing Liu",
  "publisher": "Springer",
  "qty": 3.0,
  "amount": 1295.0,
  "subject": "Web Intelligence and Mining",
  "subjectCode": "BTAI14604",
  "semester": 6,
  "recBy": "Dr. Mitali Desai",
  "dept": "AIDS"
 },
 {
  "title": "Agile Software Development, Principles, Patterns, and Practices",
  "author": "Robert C. Martin & Micah Martin",
  "publisher": "Pearson",
  "qty": 3.0,
  "amount": 699.0,
  "subject": "Agile Development and UX Design",
  "subjectCode": "BTIT14701",
  "semester": 7,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "The UX Book: Agile UX Design for a Quality User Experience, 2nd Edn.",
  "author": "Rex Hartson & Pardha S. Pyla",
  "publisher": "Morgan Kaufmann (Import)",
  "qty": 3.0,
  "amount": 5000.0,
  "subject": "Agile Development and UX Design",
  "subjectCode": "BTIT14701",
  "semester": 7,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Blockchain Blueprint for a New Economy",
  "author": "Melanie Swan",
  "publisher": "O'Reilly (Import)",
  "qty": 3.0,
  "amount": 900.0,
  "subject": "Blockchain Technology and Applications",
  "subjectCode": "BTIT14702",
  "semester": 7,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Blockchain For Dummies, 3rd Edn.",
  "author": "Tiana Laurence",
  "publisher": "Wiley (Import)",
  "qty": 3.0,
  "amount": 1300.0,
  "subject": "Blockchain Technology and Applications",
  "subjectCode": "BTIT14702",
  "semester": 7,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Blockchain Technology",
  "author": "Chandramouli Subramanian, Asha George, Abhilash K A, Meena Karthikeyan",
  "publisher": "Universities Press",
  "qty": 3.0,
  "amount": 450.0,
  "subject": "Blockchain Technology and Applications",
  "subjectCode": "BTIT14702",
  "semester": 7,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Deep Learning",
  "author": "Ian Goodfellow, Yoshua Bengio & Aaron Courville",
  "publisher": "MIT Press",
  "qty": 3.0,
  "amount": 4800.0,
  "subject": "Deep Learning",
  "subjectCode": "BTAI13701",
  "semester": 7,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Hands-On Machine Learning with Scikit-Learn and PyTorch: Concepts, Tools, and Techniques to Build Intelligent Systems",
  "author": "Aurelien Geron",
  "publisher": "Shroff/O'Reilly",
  "qty": 1.0,
  "amount": 3600.0,
  "subject": "Deep Learning",
  "subjectCode": "BTAI13701",
  "semester": 7,
  "recBy": "Dr. Vivek Champaneria",
  "dept": "AIDS"
 },
 {
  "title": "Hands-On Machine Learning with Scikit-Learn, Keras and TensorFlow",
  "author": "Aurelien Geron",
  "publisher": "O'Reilly / Shroff Publishers",
  "qty": 5.0,
  "amount": 1100.0,
  "subject": "Deep Learning",
  "subjectCode": "BTAI13701",
  "semester": 7,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Neural Networks - A Class Room Approach, 2nd Edition",
  "author": "Satish Kumar",
  "publisher": "Tata McGraw-Hill",
  "qty": 5.0,
  "amount": 650.0,
  "subject": "Deep Learning",
  "subjectCode": "BTAI13701",
  "semester": 7,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Neural Networks and Learning Machines, 3rd Edition",
  "author": "Simon Haykin",
  "publisher": "Prentice Hall of India (Pearson)",
  "qty": 5.0,
  "amount": 900.0,
  "subject": "Deep Learning",
  "subjectCode": "BTAI13701",
  "semester": 7,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Pattern Recognition and Machine Learning",
  "author": "Christopher M. Bishop",
  "publisher": "Springer (India reprint)",
  "qty": 3.0,
  "amount": 1300.0,
  "subject": "Deep Learning",
  "subjectCode": "BTAI13701",
  "semester": 7,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Beginning Blockchain",
  "author": "Bikramaditya Singhal, Gautam Dhameja & Priyansu Sekhar Panda",
  "publisher": "Apress (Import)",
  "qty": 3.0,
  "amount": 3500.0,
  "subject": "Fundamentals of Blockchain Technology",
  "subjectCode": "BTIT15701",
  "semester": 7,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Bitcoin and Cryptocurrency Technologies",
  "author": "Arvind Narayanan, Joseph Bonneau, Edward Felten, Andrew Miller & Steven Goldfeder",
  "publisher": "Princeton University Press (Import)",
  "qty": 3.0,
  "amount": 3000.0,
  "subject": "Fundamentals of Blockchain Technology",
  "subjectCode": "BTIT15701",
  "semester": 7,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Mastering Blockchain",
  "author": "Imran Bashir",
  "publisher": "Packt (Import)",
  "qty": 3.0,
  "amount": 2800.0,
  "subject": "Fundamentals of Blockchain Technology",
  "subjectCode": "BTIT15701",
  "semester": 7,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "21 Internet of Things Experiments",
  "author": "Yashwant Kanetkar",
  "publisher": "BPB Publications",
  "qty": 3.0,
  "amount": 395.0,
  "subject": "IOT and Applications",
  "subjectCode": "BTIT14704",
  "semester": 7,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "An Introduction to Internet of Things",
  "author": "Rahul Dubey",
  "publisher": "Cengage India",
  "qty": 3.0,
  "amount": 450.0,
  "subject": "IOT and Applications",
  "subjectCode": "BTIT14704",
  "semester": 7,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Getting Started with Raspberry Pi, 3rd Edn.",
  "author": "Matt Richardson, Shawn Wallace & Wolfram Donat",
  "publisher": "Maker Media/Shroff",
  "qty": 3.0,
  "amount": 650.0,
  "subject": "IOT and Applications",
  "subjectCode": "BTIT14704",
  "semester": 7,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Internet of Things - A Hands-on Approach",
  "author": "Arshdeep Bahga & Vijay Madisetti",
  "publisher": "Universities Press",
  "qty": 3.0,
  "amount": 725.0,
  "subject": "IOT and Applications",
  "subjectCode": "BTIT14704",
  "semester": 7,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Internet of Things: Architecture and Design Principles, 2nd Edn.",
  "author": "Raj Kamal",
  "publisher": "McGraw Hill India",
  "qty": 3.0,
  "amount": 575.0,
  "subject": "IOT and Applications",
  "subjectCode": "BTIT14704",
  "semester": 7,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Raspberry Pi Cookbook, 2nd Edn.",
  "author": "Simon Monk",
  "publisher": "O'Reilly (Import)",
  "qty": 3.0,
  "amount": 1300.0,
  "subject": "IOT and Applications",
  "subjectCode": "BTIT14704",
  "semester": 7,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Data Mining: Concepts and Techniques",
  "author": "Jiawei Han & Micheline Kamber",
  "publisher": "Morgan Kaufmann (Import)",
  "qty": 3.0,
  "amount": 2200.0,
  "subject": "Introduction to Machine Learning",
  "subjectCode": "BTIT15702",
  "semester": 7,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Machine Learning",
  "author": "Tom M. Mitchell",
  "publisher": "McGraw Hill",
  "qty": 3.0,
  "amount": 650.0,
  "subject": "Introduction to Machine Learning",
  "subjectCode": "BTIT15702",
  "semester": 7,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Machine Learning: The Art and Science of Algorithms that Make Sense of Data",
  "author": "Peter Flach",
  "publisher": "Cambridge University Press (Import)",
  "qty": 3.0,
  "amount": 2500.0,
  "subject": "Introduction to Machine Learning",
  "subjectCode": "BTIT15702",
  "semester": 7,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Introduction to Natural Language Processing",
  "author": "Jacob Eisenstein",
  "publisher": "MIT Press (Import)",
  "qty": 3.0,
  "amount": 3500.0,
  "subject": "Natural Language Processing",
  "subjectCode": "BTAI13702",
  "semester": 7,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Natural Language Processing in Action",
  "author": "Hobson Lane, Cole Howard & Hannes Hapke",
  "publisher": "Manning (Import)",
  "qty": 3.0,
  "amount": 3000.0,
  "subject": "Natural Language Processing",
  "subjectCode": "BTAI13702",
  "semester": 7,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Natural Language Processing with Python",
  "author": "Steven Bird, Ewan Klein & Edward Loper",
  "publisher": "Shroff/O'Reilly",
  "qty": 3.0,
  "amount": 650.0,
  "subject": "Natural Language Processing",
  "subjectCode": "BTAI13702",
  "semester": 7,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Natural Language Understanding, 2nd Edn.",
  "author": "James Allen",
  "publisher": "Pearson Education",
  "qty": 3.0,
  "amount": 850.0,
  "subject": "Natural Language Processing",
  "subjectCode": "BTAI13702",
  "semester": 7,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Speech and Language Processing, 2nd Edn.",
  "author": "Daniel Jurafsky & James H. Martin",
  "publisher": "Pearson Education",
  "qty": 3.0,
  "amount": 950.0,
  "subject": "Natural Language Processing",
  "subjectCode": "BTAI13702",
  "semester": 7,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Software Engineering",
  "author": "Rajib Mall",
  "publisher": "PHI Learning",
  "qty": 3.0,
  "amount": 450.0,
  "subject": "Software Testing",
  "subjectCode": "BTIT14703",
  "semester": 7,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Software Testing: A Craftsman's Approach, 4th Edn.",
  "author": "C. J. Paul",
  "publisher": "CRC Press (Import)",
  "qty": 3.0,
  "amount": 5500.0,
  "subject": "Software Testing",
  "subjectCode": "BTIT14703",
  "semester": 7,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Software Testing: Principles and Practices",
  "author": "Srinivasan Desikan & Gopalaswamy Ramesh",
  "publisher": "Pearson Education",
  "qty": 3.0,
  "amount": 650.0,
  "subject": "Software Testing",
  "subjectCode": "BTIT14703",
  "semester": 7,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "The Art of Software Testing, 3rd Edn.",
  "author": "G. J. Myers",
  "publisher": "Wiley Interscience (Import)",
  "qty": 3.0,
  "amount": 2800.0,
  "subject": "Software Testing",
  "subjectCode": "BTIT14703",
  "semester": 7,
  "recBy": "Prof. Bhumika",
  "dept": "AIDS"
 },
 {
  "title": "Responsible AI: Best Practices for Creating Trustworthy AI Systems",
  "author": "Qinghua Lu, Liming Zhu, Jon Whittle, Xiwei Xu)",
  "publisher": "Addison-Wesley Professional",
  "qty": 1.0,
  "amount": 3489.0,
  "subject": "Advances in AI",
  "subjectCode": "",
  "semester": null,
  "recBy": "Prof.Mukesh Patel",
  "dept": "AIDS"
 },
 {
  "title": "Bio-Inspired Artificial Intelligence: Theories, Methods, and Technologies",
  "author": "Dario Floreano and Claudio Mattiussi",
  "publisher": "MIT",
  "qty": 3.0,
  "amount": 6500.0,
  "subject": "Artificial Intelligence",
  "subjectCode": "",
  "semester": null,
  "recBy": "Dr. Mita Parikh",
  "dept": "AIDS"
 },
 {
  "title": "First Course In Artificial Intelligence",
  "author": "Deepak Khemani",
  "publisher": "McGraw Hill Education (India)",
  "qty": 3.0,
  "amount": 600.0,
  "subject": "Artificial Intelligence",
  "subjectCode": "",
  "semester": null,
  "recBy": "Dr. Vibha Patel",
  "dept": "AIDS"
 },
 {
  "title": "Search Methods in Artificial Intelligence",
  "author": "Deepak Khemani",
  "publisher": "Cambridge University Press",
  "qty": 3.0,
  "amount": 720.0,
  "subject": "Artificial Intelligence",
  "subjectCode": "",
  "semester": null,
  "recBy": "Dr. Vibha Patel",
  "dept": "AIDS"
 },
 {
  "title": "Blockchain Technology",
  "author": "Chandramouli Subramanian, Asha A George, Abhilash K A and MeenaKarthikeyan",
  "publisher": "Universities Press",
  "qty": 2.0,
  "amount": 1150.0,
  "subject": "Blockchain Technology and Applications",
  "subjectCode": "",
  "semester": null,
  "recBy": "Prof. Dhaval Rana",
  "dept": "AIDS"
 },
 {
  "title": "Deep Learning (Adaptive Computation and Machine Learning series)",
  "author": "Ian Goodfellow, Yoshua Bengio, Aaron Courville",
  "publisher": "MIT",
  "qty": 2.0,
  "amount": 9645.0,
  "subject": "Deep Learning",
  "subjectCode": "",
  "semester": null,
  "recBy": "Prof. Karishma H. Desai",
  "dept": "AIDS"
 },
 {
  "title": "Practical Statistics for Data Scientists",
  "author": "Peter Bruce and Andrew Bruce",
  "publisher": "O'Reilly Media, Inc.",
  "qty": 3.0,
  "amount": 8439.0,
  "subject": "Fundamentals of Data Science",
  "subjectCode": "",
  "semester": null,
  "recBy": "Dr. Krishna Delvadia",
  "dept": "AIDS"
 },
 {
  "title": "Introduction to Large Language Models -Generative AI for Text",
  "author": "Tanmoy Chakraborty",
  "publisher": "Wiley Publication",
  "qty": 5.0,
  "amount": 899.0,
  "subject": "Language Models",
  "subjectCode": "",
  "semester": null,
  "recBy": "Prof. Palak Desai",
  "dept": "AIDS"
 },
 {
  "title": "Machine Learning: A Probabilistic Perspective",
  "author": "Kevin P. Murphy",
  "publisher": "Publisher N/A",
  "qty": 3.0,
  "amount": 6725.0,
  "subject": "Machine Learning",
  "subjectCode": "",
  "semester": null,
  "recBy": "Dr. Mita Parikh",
  "dept": "AIDS"
 },
 {
  "title": "Speech and Language Processing",
  "author": "Daniel Jurafsky, James H. Martin",
  "publisher": "Pearson",
  "qty": 3.0,
  "amount": 1120.0,
  "subject": "Natural Language Processing",
  "subjectCode": "",
  "semester": null,
  "recBy": "Dr. Mita Parikh",
  "dept": "AIDS"
 },
 {
  "title": "C Programming language",
  "author": "Kernighan B W and Ritchie D M",
  "publisher": "Prentice Hall",
  "qty": null,
  "amount": 503.0,
  "subject": "Programming for Problem Solving",
  "subjectCode": "BTCO12107",
  "semester": 1,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Core Python Programming",
  "author": "R. Nageswara Rao",
  "publisher": "Dreamtech",
  "qty": null,
  "amount": 649.0,
  "subject": "Programming for Problem Solving",
  "subjectCode": "BTCO12107",
  "semester": 1,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Fundamentals of Python - First Programs",
  "author": "Kenneth A. Lambert",
  "publisher": "CENGAGE Publication",
  "qty": null,
  "amount": null,
  "subject": "Programming for Problem Solving",
  "subjectCode": "BTCO12107",
  "semester": 1,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Let Us C",
  "author": "Kanetkar Y. P.",
  "publisher": "BPB Publication",
  "qty": null,
  "amount": null,
  "subject": "Programming for Problem Solving",
  "subjectCode": "BTCO12107",
  "semester": 1,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Programming in ANSI C",
  "author": "Balagarusamy E",
  "publisher": "Tata McGraw-Hill",
  "qty": null,
  "amount": 725.0,
  "subject": "Programming for Problem Solving",
  "subjectCode": "BTCO12107",
  "semester": 1,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Programming in C",
  "author": "B. Gottfried",
  "publisher": "Tata Mc-Graw Hill",
  "qty": null,
  "amount": 550.0,
  "subject": "Programming for Problem Solving",
  "subjectCode": "BTCO12107",
  "semester": 1,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Computer System Architecture",
  "author": "M. Morris Mano",
  "publisher": "Pearson Education",
  "qty": null,
  "amount": 975.0,
  "subject": "Computer Organization and Architecture",
  "subjectCode": "BTCO13302",
  "semester": 3,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Digital Fundamentals",
  "author": "Floyed Thomas L. and Jain R. P.",
  "publisher": "Pearson Education",
  "qty": null,
  "amount": 391.0,
  "subject": "Computer Organization and Architecture",
  "subjectCode": "BTCO13302",
  "semester": 3,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Fundamentals of Digital Circuits",
  "author": "A. Kumar",
  "publisher": "Prentice Hall India",
  "qty": null,
  "amount": 475.0,
  "subject": "Computer Organization and Architecture",
  "subjectCode": "BTCO13302",
  "semester": 3,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "An Introduction to Data Structures with Applications",
  "author": "Jean-Paul Tremblay, Paul G. Sorenson",
  "publisher": "McGraw Hill Education",
  "qty": null,
  "amount": null,
  "subject": "Data Structures",
  "subjectCode": "BTIT13302",
  "semester": 3,
  "recBy": "-",
  "dept": "IT"
 },
 {
  "title": "Data Structures Using C",
  "author": "E. Balagurusamy",
  "publisher": "McGraw Hill",
  "qty": null,
  "amount": 499.0,
  "subject": "Data Structures",
  "subjectCode": "BTIT13302",
  "semester": 3,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "8086 Programming and Advance Processor Architecture",
  "author": "M. T. Savaliya",
  "publisher": "Wiley India",
  "qty": null,
  "amount": null,
  "subject": "Microprocessor and Interfacing",
  "subjectCode": "BTCO13303",
  "semester": 3,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Microprocessor Architecture, Programming, and Applications with the 8085",
  "author": "Ramesh S. Gaonkar",
  "publisher": "Penram International",
  "qty": null,
  "amount": 860.0,
  "subject": "Microprocessor and Interfacing",
  "subjectCode": "BTCO13303",
  "semester": 3,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Microprocessors & Interfacing",
  "author": "Douglas Hall",
  "publisher": "TMH",
  "qty": null,
  "amount": 900.0,
  "subject": "Microprocessor and Interfacing",
  "subjectCode": "BTCO13303",
  "semester": 3,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "The 8088 and 8086 Microprocessors",
  "author": "Triebel & Singh",
  "publisher": "Pearson Education",
  "qty": null,
  "amount": 1280.0,
  "subject": "Microprocessor and Interfacing",
  "subjectCode": "BTCO13303",
  "semester": 3,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Core Java, Volume I: Fundamentals",
  "author": "Cay S. Horstmann, Gary Cornell",
  "publisher": "Pearson Education",
  "qty": null,
  "amount": 950.0,
  "subject": "Object Oriented Programming",
  "subjectCode": "BTCO13304",
  "semester": 3,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Introduction to Java Programming and Data Structures, Comprehensive Version",
  "author": "Y. Daniel Liang",
  "publisher": "Pearson Education",
  "qty": null,
  "amount": 1350.0,
  "subject": "Object Oriented Programming",
  "subjectCode": "BTCO13304",
  "semester": 3,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Java Fundamentals",
  "author": "Herbert Schildt, Dale Skrien",
  "publisher": "McGraw Hill Education",
  "qty": null,
  "amount": 960.0,
  "subject": "Object Oriented Programming",
  "subjectCode": "BTCO13304",
  "semester": 3,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Java: The Complete Reference",
  "author": "Herbert Schildt",
  "publisher": "Oracle Press / McGraw Hill",
  "qty": null,
  "amount": 1200.0,
  "subject": "Object Oriented Programming",
  "subjectCode": "BTCO13304",
  "semester": 3,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Computer Networking: A Top-Down Approach",
  "author": "Kurose, Ross",
  "publisher": "Pearson",
  "qty": null,
  "amount": 899.0,
  "subject": "Computer Networks",
  "subjectCode": "BTCO13401",
  "semester": 4,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Computer Networks",
  "author": "Andrew S. Tanenbaum",
  "publisher": "Prentice Hall",
  "qty": null,
  "amount": 699.0,
  "subject": "Computer Networks",
  "subjectCode": "BTCO13401",
  "semester": 4,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Data Communications and Networking",
  "author": "Behrouz Forouzan",
  "publisher": "McGraw Hill",
  "qty": null,
  "amount": 899.0,
  "subject": "Computer Networks",
  "subjectCode": "BTCO13401",
  "semester": 4,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "An Introduction to Database Systems",
  "author": "C. J. Date",
  "publisher": "Pearson",
  "qty": null,
  "amount": 699.0,
  "subject": "Database Management Systems",
  "subjectCode": "BTCO13404",
  "semester": 4,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Database System Concepts",
  "author": "Silberschatz, Henry F. Korth, S. Sudarshan",
  "publisher": "McGraw-Hill",
  "qty": null,
  "amount": 699.0,
  "subject": "Database Management Systems",
  "subjectCode": "BTCO13404",
  "semester": 4,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Fundamentals of Database Systems",
  "author": "R. Elmasri, S. Navathe",
  "publisher": "Prentice Hall/Pearson",
  "qty": null,
  "amount": 799.0,
  "subject": "Database Management Systems",
  "subjectCode": "BTCO13404",
  "semester": 4,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "SQL-PL/SQL",
  "author": "Ivan Bayross",
  "publisher": "BPB",
  "qty": null,
  "amount": 450.0,
  "subject": "Database Management Systems",
  "subjectCode": "BTCO13404",
  "semester": 4,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Fundamentals of Algorithmics",
  "author": "Gilles Brassard, Paul Bratley",
  "publisher": "Pearson",
  "qty": null,
  "amount": null,
  "subject": "Design & Analysis of Algorithms",
  "subjectCode": "BTCO13403",
  "semester": 4,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Fundamentals of Computer Algorithms",
  "author": "Ellis Horowitz, Sartaj Sahni",
  "publisher": "Pearson",
  "qty": null,
  "amount": 599.0,
  "subject": "Design & Analysis of Algorithms",
  "subjectCode": "BTCO13403",
  "semester": 4,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Introduction to Algorithms",
  "author": "Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein",
  "publisher": "PHI (ISBN 978-81-203-2142-0)",
  "qty": null,
  "amount": null,
  "subject": "Design & Analysis of Algorithms",
  "subjectCode": "BTCO13403",
  "semester": 4,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Modern Operating Systems",
  "author": "Andrew S. Tanenbaum",
  "publisher": "Prentice Hall",
  "qty": null,
  "amount": 699.0,
  "subject": "Operating Systems",
  "subjectCode": "BTCO13402",
  "semester": 4,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Operating System Concepts",
  "author": "Silberschatz, Peter B. Galvin, Greg Gagne",
  "publisher": "Wiley",
  "qty": null,
  "amount": 599.0,
  "subject": "Operating Systems",
  "subjectCode": "BTCO13402",
  "semester": 4,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Operating Systems: Internals and Design Principles",
  "author": "William Stallings",
  "publisher": "Pearson",
  "qty": null,
  "amount": 799.0,
  "subject": "Operating Systems",
  "subjectCode": "BTCO13402",
  "semester": 4,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "UNIX Shell Programming",
  "author": "Yashwant Kanetkar",
  "publisher": "BPB",
  "qty": null,
  "amount": 250.0,
  "subject": "Operating Systems",
  "subjectCode": "BTCO13402",
  "semester": 4,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Unix Concepts and Applications",
  "author": "Sumitabha Das",
  "publisher": "McGraw Hill",
  "qty": null,
  "amount": 599.0,
  "subject": "Operating Systems",
  "subjectCode": "BTCO13402",
  "semester": 4,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Cloud Computing Bible",
  "author": "Sosinsky B",
  "publisher": "Wiley India",
  "qty": null,
  "amount": 2899.0,
  "subject": "Cloud Computing",
  "subjectCode": "BTIT14502",
  "semester": 5,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Cloud Computing – A Practical Approach",
  "author": "Velte T., Velte A., Elsenpeter R.",
  "publisher": "Tata McGrawHill",
  "qty": null,
  "amount": 475.0,
  "subject": "Cloud Computing",
  "subjectCode": "BTIT14502",
  "semester": 5,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Cloud Computing: Principles and Paradigms",
  "author": "Rajkumar Buyya",
  "publisher": "Wiley India Edition",
  "qty": null,
  "amount": null,
  "subject": "Cloud Computing",
  "subjectCode": "BTIT14502",
  "semester": 5,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Cloud Security: A Comprehensive Guide to Secure Cloud Computing",
  "author": "Ronald L. Krutz, Russell Dean Vines",
  "publisher": "Wiley",
  "qty": null,
  "amount": null,
  "subject": "Cloud Computing",
  "subjectCode": "BTIT14502",
  "semester": 5,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Applied Cryptography: Protocols, Algorithms, and Source Code in C",
  "author": "Bruce Schneier",
  "publisher": "John Wiley & Sons",
  "qty": null,
  "amount": 4318.0,
  "subject": "Cryptography and Network Security",
  "subjectCode": "BTIT13502",
  "semester": 5,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Cryptography & Network Security",
  "author": "Behrouz A. Forouzan",
  "publisher": "McGraw-Hill",
  "qty": null,
  "amount": 775.0,
  "subject": "Cryptography and Network Security",
  "subjectCode": "BTIT13502",
  "semester": 5,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Cryptography and Network Security: Principles and Practice",
  "author": "William Stallings",
  "publisher": "Pearson",
  "qty": null,
  "amount": 664.0,
  "subject": "Cryptography and Network Security",
  "subjectCode": "BTIT13502",
  "semester": 5,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Cryptography: Theory and Practice",
  "author": "Douglas R. Stinson",
  "publisher": "Chapman and Hall/CRC",
  "qty": null,
  "amount": null,
  "subject": "Cryptography and Network Security",
  "subjectCode": "BTIT13502",
  "semester": 5,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Information Security Principles and Practice",
  "author": "Mark Stamp",
  "publisher": "Wiley India Edition",
  "qty": null,
  "amount": null,
  "subject": "Cryptography and Network Security",
  "subjectCode": "BTIT13502",
  "semester": 5,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Security in Computing",
  "author": "Pfleeger and Pfleeger",
  "publisher": "PHI",
  "qty": null,
  "amount": null,
  "subject": "Cryptography and Network Security",
  "subjectCode": "BTIT13502",
  "semester": 5,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Cyber-Physical Systems",
  "author": "Raj Rajkumar, Dionisio de Niz, Mark Klein",
  "publisher": "Addison-Wesley",
  "qty": null,
  "amount": null,
  "subject": "Cyber Physical Systems",
  "subjectCode": "BTIT14503",
  "semester": 5,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Cyber-Physical Systems",
  "author": "Fei Hu",
  "publisher": "CRC Press",
  "qty": null,
  "amount": null,
  "subject": "Cyber Physical Systems",
  "subjectCode": "BTIT14503",
  "semester": 5,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Introduction to Embedded Systems: A Cyber-Physical Systems Approach",
  "author": "E. A. Lee, S. A. Seshia",
  "publisher": "MIT Press",
  "qty": null,
  "amount": null,
  "subject": "Cyber Physical Systems",
  "subjectCode": "BTIT14503",
  "semester": 5,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Principles of Cyber-Physical Systems",
  "author": "R. Alur",
  "publisher": "MIT Press",
  "qty": null,
  "amount": null,
  "subject": "Cyber Physical Systems",
  "subjectCode": "BTIT14503",
  "semester": 5,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Data Mining for Business Applications",
  "author": "Longbing Cao, Philip S. Yu, Chengqi Zhang, Huaifeng Zhang",
  "publisher": "Springer",
  "qty": null,
  "amount": null,
  "subject": "Data Mining and Business Intelligence",
  "subjectCode": "BTIT13501",
  "semester": 5,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Data Mining for Business Intelligence",
  "author": "Shmueli, Bruce, Yahav, Patel, Lichtendahl Jr.",
  "publisher": "Wiley",
  "qty": null,
  "amount": null,
  "subject": "Data Mining and Business Intelligence",
  "subjectCode": "BTIT13501",
  "semester": 5,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Data Mining: Concepts and Techniques",
  "author": "J. Han, M. Kamber",
  "publisher": "Morgan Kaufmann",
  "qty": null,
  "amount": 5231.0,
  "subject": "Data Mining and Business Intelligence",
  "subjectCode": "BTIT13501",
  "semester": 5,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Data Mining: Introductory and Advanced Topics",
  "author": "M. Dunham",
  "publisher": "Pearson Education",
  "qty": null,
  "amount": null,
  "subject": "Data Mining and Business Intelligence",
  "subjectCode": "BTIT13501",
  "semester": 5,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Applied Statistics & Probability for Engineering",
  "author": "Douglas Montgomery, George Runger",
  "publisher": "John Wiley & Sons, Inc",
  "qty": null,
  "amount": null,
  "subject": "Data Science using Python",
  "subjectCode": "BTIT15501",
  "semester": 5,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Data Science for Dummies",
  "author": "John Muller",
  "publisher": "Wiley",
  "qty": null,
  "amount": null,
  "subject": "Data Science using Python",
  "subjectCode": "BTIT15501",
  "semester": 5,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Mastering Python for Data Science",
  "author": "Samir Madhavan",
  "publisher": "Ingram short title",
  "qty": null,
  "amount": null,
  "subject": "Data Science using Python",
  "subjectCode": "BTIT15501",
  "semester": 5,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Practical Statistics for Data Scientists",
  "author": "Peter Bruce, Andrew Bruce",
  "publisher": "O'Reilly Media",
  "qty": null,
  "amount": null,
  "subject": "Data Science using Python",
  "subjectCode": "BTIT15501",
  "semester": 5,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Python for Data Analysis: Data Wrangling with Pandas, NumPy, and IPython",
  "author": "McKinney, W.",
  "publisher": "O'Reilly Media, Inc.",
  "qty": null,
  "amount": null,
  "subject": "Data Science using Python",
  "subjectCode": "BTIT15501",
  "semester": 5,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "ICT in Agriculture: Connecting Smallholders to Knowledge, Networks, and Institutions",
  "author": "(World Bank)",
  "publisher": "The World Bank (Report No. 64605)",
  "qty": null,
  "amount": null,
  "subject": "ICT in Agriculture",
  "subjectCode": "BTIT14504",
  "semester": 5,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Information and Communication Technology for Agriculture and Rural Development",
  "author": "R. Saravanan, C. Kathiresan, T. Indra Devi",
  "publisher": "New India Publishing Agency",
  "qty": null,
  "amount": null,
  "subject": "ICT in Agriculture",
  "subjectCode": "BTIT14504",
  "semester": 5,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Textbook of Agricultural Communication Process and Methods",
  "author": "A. S. Sandhu",
  "publisher": "Oxford & IBH Publishing Co Pvt. Ltd",
  "qty": null,
  "amount": null,
  "subject": "ICT in Agriculture",
  "subjectCode": "BTIT14504",
  "semester": 5,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Core Java, Volume I: Fundamentals",
  "author": "Cay S. Horstmann, Gray Cornell",
  "publisher": "Pearson Education",
  "qty": null,
  "amount": 950.0,
  "subject": "Programming with Java",
  "subjectCode": "BTIT15502",
  "semester": 5,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "An Integrated Approach to Software Engineering",
  "author": "Pankaj Jalote",
  "publisher": "Narosa",
  "qty": null,
  "amount": 762.0,
  "subject": "Software Engineering",
  "subjectCode": "BTIT14501",
  "semester": 5,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Fundamentals of Software Engineering",
  "author": "Rajib Mall",
  "publisher": "PHI",
  "qty": null,
  "amount": null,
  "subject": "Software Engineering",
  "subjectCode": "BTIT14501",
  "semester": 5,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Software Engineering",
  "author": "Ian Sommerville",
  "publisher": "Pearson Education",
  "qty": null,
  "amount": null,
  "subject": "Software Engineering",
  "subjectCode": "BTIT14501",
  "semester": 5,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Software Engineering: A Practitioner's Approach",
  "author": "Roger S. Pressman",
  "publisher": "McGraw-Hill",
  "qty": null,
  "amount": 875.0,
  "subject": "Software Engineering",
  "subjectCode": "BTIT14501",
  "semester": 5,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Developing Web Applications, 2nd Ed",
  "author": "Ralph Moseley, M. T. Savaliya",
  "publisher": "Wiley India",
  "qty": null,
  "amount": null,
  "subject": "Web Technologies",
  "subjectCode": "BTCO13502",
  "semester": 5,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Fundamentals of Web Development, 2nd Ed",
  "author": "Randy Connolly, Ricardo Hoar",
  "publisher": "Pearson",
  "qty": null,
  "amount": 936.0,
  "subject": "Web Technologies",
  "subjectCode": "BTCO13502",
  "semester": 5,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "HTML 5 Black Book, 2nd Ed",
  "author": "DT Editorial Services",
  "publisher": "Dreamtech Press",
  "qty": null,
  "amount": 599.0,
  "subject": "Web Technologies",
  "subjectCode": "BTCO13502",
  "semester": 5,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Learning PHP, MySQL & JavaScript with jQuery, CSS and HTML5, 4th Ed",
  "author": "Robin Nixon",
  "publisher": "O'Reilly Media",
  "qty": null,
  "amount": null,
  "subject": "Web Technologies",
  "subjectCode": "BTCO13502",
  "semester": 5,
  "recBy": "-",
  "dept": "IT"
 },
 {
  "title": "PHP: The Complete Reference",
  "author": "Steven Holzner",
  "publisher": "McGraw Hill",
  "qty": null,
  "amount": 450.0,
  "subject": "Web Technologies",
  "subjectCode": "BTCO13502",
  "semester": 5,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Artificial Intelligence",
  "author": "Elaine Rich, Kevin Knight",
  "publisher": "Tata McGraw-Hill",
  "qty": null,
  "amount": null,
  "subject": "AI and Applications",
  "subjectCode": "BTIT13602",
  "semester": 6,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Artificial Intelligence: A Modern Approach",
  "author": "Stuart J. Russell, Peter Norvig",
  "publisher": "Pearson",
  "qty": null,
  "amount": 899.0,
  "subject": "AI and Applications",
  "subjectCode": "BTIT13602",
  "semester": 6,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Fuzzy Logic: An Introductory Course for Engineering Students",
  "author": "Enric Trillas, Luka Eciolaza",
  "publisher": "Springer",
  "qty": null,
  "amount": null,
  "subject": "AI and Applications",
  "subjectCode": "BTIT13602",
  "semester": 6,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Introduction to Artificial Intelligence and Expert Systems",
  "author": "Dan W. Patterson",
  "publisher": "PHI Learning",
  "qty": null,
  "amount": null,
  "subject": "AI and Applications",
  "subjectCode": "BTIT13602",
  "semester": 6,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Introduction to Turbo PROLOG",
  "author": "Carl Townsend",
  "publisher": "BPB Publications",
  "qty": null,
  "amount": null,
  "subject": "AI and Applications",
  "subjectCode": "BTIT13602",
  "semester": 6,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Knowledge Representation and Reasoning",
  "author": "Ron Brachman, Hector Levesque",
  "publisher": "Morgan Kaufmann",
  "qty": null,
  "amount": null,
  "subject": "AI and Applications",
  "subjectCode": "BTIT13602",
  "semester": 6,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "PROLOG Programming for Artificial Intelligence",
  "author": "Ivan Bratko",
  "publisher": "Addison-Wesley",
  "qty": null,
  "amount": null,
  "subject": "AI and Applications",
  "subjectCode": "BTIT13602",
  "semester": 6,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "MongoDB Cookbook",
  "author": "Cyrus Dasadia, Amol Nayak",
  "publisher": "Packt Publication",
  "qty": null,
  "amount": null,
  "subject": "Advanced Web Technology",
  "subjectCode": "BTIT14603",
  "semester": 6,
  "recBy": "-",
  "dept": "IT"
 },
 {
  "title": "Node.Js in Practice",
  "author": "Alex Young, Marc Harter, Ben Noordhuis",
  "publisher": "Manning Publications",
  "qty": null,
  "amount": null,
  "subject": "Advanced Web Technology",
  "subjectCode": "BTIT14603",
  "semester": 6,
  "recBy": "-",
  "dept": "IT"
 },
 {
  "title": "Node.js in Action",
  "author": "Alex Young, Bradley Meck, Mike Cantelon, Tim Oxley, Marc Harter, T.J. Holowaychuk, Nathan Rajlich",
  "publisher": "Manning Publications",
  "qty": null,
  "amount": null,
  "subject": "Advanced Web Technology",
  "subjectCode": "BTIT14603",
  "semester": 6,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Professional Node.js",
  "author": "Pedro Teixeira",
  "publisher": "Wiley",
  "qty": null,
  "amount": null,
  "subject": "Advanced Web Technology",
  "subjectCode": "BTIT14603",
  "semester": 6,
  "recBy": "-",
  "dept": "IT"
 },
 {
  "title": "The Road to Learn React",
  "author": "Robin Wieruch",
  "publisher": "Wiley",
  "qty": null,
  "amount": null,
  "subject": "Advanced Web Technology",
  "subjectCode": "BTIT14603",
  "semester": 6,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Computer Graphics with OpenGL",
  "author": "Donald D. Hearn",
  "publisher": "Pearson Education (ISBN 9789332518711)",
  "qty": null,
  "amount": null,
  "subject": "Computer Graphics",
  "subjectCode": "BTIT14601",
  "semester": 6,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Computer Graphics, C Version – Anna University",
  "author": "Donald D. Hearn",
  "publisher": "Pearson Education (ISBN 9789332518711)",
  "qty": null,
  "amount": null,
  "subject": "Computer Graphics",
  "subjectCode": "BTIT14601",
  "semester": 6,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "A Guide for Machine Vision in Quality Control",
  "author": "Sheila Anand, Priya",
  "publisher": "CRC Press Inc",
  "qty": null,
  "amount": null,
  "subject": "Computer Vision",
  "subjectCode": "BTIT14605",
  "semester": 6,
  "recBy": "-",
  "dept": "IT"
 },
 {
  "title": "Computer Vision – A Modern Approach",
  "author": "Forsyth, Ponce",
  "publisher": "Prentice Hall",
  "qty": null,
  "amount": null,
  "subject": "Computer Vision",
  "subjectCode": "BTIT14605",
  "semester": 6,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Doing Data Science: Straight Talk from the Frontline",
  "author": "Cathy O'Neil",
  "publisher": "O'Reilly Media",
  "qty": null,
  "amount": 3299.0,
  "subject": "Data Analysis & Visualization",
  "subjectCode": "BTIT13601",
  "semester": 6,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Python for Data Analysis: Data Wrangling with Pandas, NumPy and IPython",
  "author": "Wes McKinney",
  "publisher": "O'Reilly Media",
  "qty": null,
  "amount": 999.0,
  "subject": "Data Analysis & Visualization",
  "subjectCode": "BTIT13601",
  "semester": 6,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "The Art of Data Science",
  "author": "Roger Peng",
  "publisher": "Lulu.com",
  "qty": null,
  "amount": null,
  "subject": "Data Analysis & Visualization",
  "subjectCode": "BTIT13601",
  "semester": 6,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Data Compression: Methods and Theory",
  "author": "James A. Storer",
  "publisher": "Computer Science Press",
  "qty": null,
  "amount": null,
  "subject": "Data Compression",
  "subjectCode": "BTIT14608",
  "semester": 6,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Data Compression: The Complete Reference",
  "author": "David Salomon",
  "publisher": "Springer",
  "qty": null,
  "amount": null,
  "subject": "Data Compression",
  "subjectCode": "BTIT14608",
  "semester": 6,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Introduction to Data Compression",
  "author": "Khalid Sayood",
  "publisher": "Morgan Kaufmann",
  "qty": null,
  "amount": null,
  "subject": "Data Compression",
  "subjectCode": "BTIT14608",
  "semester": 6,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "The Data Compression Book",
  "author": "Mark Nelson",
  "publisher": "John Wiley & Sons",
  "qty": null,
  "amount": null,
  "subject": "Data Compression",
  "subjectCode": "BTIT14608",
  "semester": 6,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "ASP.NET Complete Reference",
  "author": "Matthew Macdonald, Robert Standefer",
  "publisher": "Tata McGraw-Hill",
  "qty": null,
  "amount": null,
  "subject": "DotNet Technology",
  "subjectCode": "BTIT14606",
  "semester": 6,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "C# The Basics",
  "author": "Vijay Mukhi",
  "publisher": "BPB",
  "qty": null,
  "amount": null,
  "subject": "DotNet Technology",
  "subjectCode": "BTIT14606",
  "semester": 6,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Professional C# .Net",
  "author": "Christian Nagel",
  "publisher": "Wrox",
  "qty": null,
  "amount": null,
  "subject": "DotNet Technology",
  "subjectCode": "BTIT14606",
  "semester": 6,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "E-Business Roadmap for Success",
  "author": "Dr. Ravi Kalakota, Marcia Robinson",
  "publisher": "Addison Wesley",
  "qty": null,
  "amount": null,
  "subject": "E-Commerce & E-Business Mgmt",
  "subjectCode": "BTIT13603",
  "semester": 6,
  "recBy": "-",
  "dept": "IT"
 },
 {
  "title": "E-business and E-commerce Management",
  "author": "Dave Chaffey",
  "publisher": "Pearson",
  "qty": null,
  "amount": 899.0,
  "subject": "E-Commerce & E-Business Mgmt",
  "subjectCode": "BTIT13603",
  "semester": 6,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "E-commerce",
  "author": "Schneider",
  "publisher": "Cengage Learning",
  "qty": null,
  "amount": null,
  "subject": "E-Commerce & E-Business Mgmt",
  "subjectCode": "BTIT13603",
  "semester": 6,
  "recBy": "-",
  "dept": "IT"
 },
 {
  "title": "E-commerce and Web Marketing",
  "author": "Hansom, Kalyanam",
  "publisher": "Cengage Learning",
  "qty": null,
  "amount": null,
  "subject": "E-Commerce & E-Business Mgmt",
  "subjectCode": "BTIT13603",
  "semester": 6,
  "recBy": "-",
  "dept": "IT"
 },
 {
  "title": "Frontiers of E-commerce",
  "author": "Ravi Kalakota",
  "publisher": "Pearson",
  "qty": null,
  "amount": null,
  "subject": "E-Commerce & E-Business Mgmt",
  "subjectCode": "BTIT13603",
  "semester": 6,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Hacking Exposed",
  "author": "Stuart McClure, Joel Scrambray, George Kurtz",
  "publisher": "Tata McGraw-Hill",
  "qty": null,
  "amount": 599.0,
  "subject": "Information Security",
  "subjectCode": "BTIT15602",
  "semester": 6,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Handbook of Information Security Management",
  "author": "Micki Krause, Harold F. Tipton",
  "publisher": "CRC Press LLC",
  "qty": null,
  "amount": null,
  "subject": "Information Security",
  "subjectCode": "BTIT15602",
  "semester": 6,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Principles of Information Security",
  "author": "Michael E. Whitman, Herbert J. Mattord",
  "publisher": "Vikas Publishing House",
  "qty": null,
  "amount": null,
  "subject": "Information Security",
  "subjectCode": "BTIT15602",
  "semester": 6,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Machine Learning",
  "author": "Tom M. Mitchell",
  "publisher": "McGraw Hill",
  "qty": null,
  "amount": 795.0,
  "subject": "Machine Learning Techniques",
  "subjectCode": "BTIT14607",
  "semester": 6,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Machine Learning: The Art and Science of Algorithms that Make Sense of Data",
  "author": "Peter Flach",
  "publisher": "Cambridge University Press",
  "qty": null,
  "amount": 895.0,
  "subject": "Machine Learning Techniques",
  "subjectCode": "BTIT14607",
  "semester": 6,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Pattern Recognition and Machine Learning",
  "author": "Christopher M. Bishop",
  "publisher": "Springer",
  "qty": null,
  "amount": 4999.0,
  "subject": "Machine Learning Techniques",
  "subjectCode": "BTIT14607",
  "semester": 6,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Android Application Development Black Book",
  "author": "Pradeep Kothari",
  "publisher": "DreamTech",
  "qty": null,
  "amount": null,
  "subject": "Mobile Application Development",
  "subjectCode": "BTIT14602",
  "semester": 6,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Android Wireless Application Development",
  "author": "Lauren Darcey",
  "publisher": "Pearson",
  "qty": null,
  "amount": null,
  "subject": "Mobile Application Development",
  "subjectCode": "BTIT14602",
  "semester": 6,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Beginning Android 4 Application Development",
  "author": "Wei Meng Lee",
  "publisher": "Wrox",
  "qty": null,
  "amount": null,
  "subject": "Mobile Application Development",
  "subjectCode": "BTIT14602",
  "semester": 6,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "MongoDB in Action",
  "author": "Kyle Banker, Peter Bakkum, Shaun Verch, Douglas Garrett, Tim Hawkins",
  "publisher": "Manning Publications (ISBN 978-9351199359)",
  "qty": null,
  "amount": null,
  "subject": "NoSQL Databases",
  "subjectCode": "BTIT14604",
  "semester": 6,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "MongoDB: The Definitive Guide",
  "author": "Kristina Chodorow",
  "publisher": "O'Reilly (ISBN 978-9351102694)",
  "qty": null,
  "amount": 599.0,
  "subject": "NoSQL Databases",
  "subjectCode": "BTIT14604",
  "semester": 6,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Innovation Management & New Product Development",
  "author": "Paul Trott",
  "publisher": "Pitman",
  "qty": null,
  "amount": null,
  "subject": "Research and Innovation",
  "subjectCode": "BTMD17608",
  "semester": 6,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Research Methodology: A Practical and Scientific Approach",
  "author": "Vinayak Bairagi, Mousami V. Munot",
  "publisher": "CRC Press",
  "qty": null,
  "amount": null,
  "subject": "Research and Innovation",
  "subjectCode": "BTMD17608",
  "semester": 6,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Research Methodology: A Step by Step Guide for Beginners",
  "author": "Ranjit Kumar",
  "publisher": "Sage Publication",
  "qty": null,
  "amount": 895.0,
  "subject": "Research and Innovation",
  "subjectCode": "BTMD17608",
  "semester": 6,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Data Mining: Concepts and Techniques",
  "author": "Jiawei Han, Micheline Kamber",
  "publisher": "Morgan Kaufmann",
  "qty": null,
  "amount": 5231.0,
  "subject": "Advanced Database Systems",
  "subjectCode": "BTIT14708",
  "semester": 7,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Distributed Database Systems",
  "author": "David Bell, Jane Grimson",
  "publisher": "Addison-Wesley",
  "qty": null,
  "amount": null,
  "subject": "Advanced Database Systems",
  "subjectCode": "BTIT14708",
  "semester": 7,
  "recBy": "-",
  "dept": "IT"
 },
 {
  "title": "Distributed Databases: Principles and Systems",
  "author": "Stefano Ceri, Giuseppe Pelagatti",
  "publisher": "McGraw Hill",
  "qty": null,
  "amount": null,
  "subject": "Advanced Database Systems",
  "subjectCode": "BTIT14708",
  "semester": 7,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Principles of Distributed Database Systems",
  "author": "M.T. Ozsu, P. Valduriez",
  "publisher": "Pearson",
  "qty": null,
  "amount": 899.0,
  "subject": "Advanced Database Systems",
  "subjectCode": "BTIT14708",
  "semester": 7,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "The UX Book: Agile UX Design for a Quality User Experience",
  "author": "Rex Hartson, Pardha S. Pyla",
  "publisher": "Morgan Kaufmann",
  "qty": null,
  "amount": null,
  "subject": "Agile Development and UX Design",
  "subjectCode": "BTIT14701",
  "semester": 7,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "An Introduction to Automata Theory and Formal Languages",
  "author": "Adesh K. Pandey",
  "publisher": "S.K. Kataria & Sons",
  "qty": null,
  "amount": 350.0,
  "subject": "Automata Theory and Compiler Design",
  "subjectCode": "BTIT13701",
  "semester": 7,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Compilers: Principles, Techniques, and Tools",
  "author": "Alfred V. Aho, Ravi Sethi, J.D. Ullman",
  "publisher": "Addison Wesley",
  "qty": null,
  "amount": 899.0,
  "subject": "Automata Theory and Compiler Design",
  "subjectCode": "BTIT13701",
  "semester": 7,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Introduction to Languages and the Theory of Computation",
  "author": "John Martin",
  "publisher": "Tata McGraw Hill",
  "qty": null,
  "amount": 699.0,
  "subject": "Automata Theory and Compiler Design",
  "subjectCode": "BTIT13701",
  "semester": 7,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Modern Compiler Design",
  "author": "Dick Grune, Henri E. Bal, J.H. Jacobs, Koen G. Langendoen",
  "publisher": "Springer",
  "qty": null,
  "amount": 4999.0,
  "subject": "Automata Theory and Compiler Design",
  "subjectCode": "BTIT13701",
  "semester": 7,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Blockchain For Dummies",
  "author": "Tiana Laurence",
  "publisher": "Wiley",
  "qty": null,
  "amount": 599.0,
  "subject": "Blockchain Technology and Applications",
  "subjectCode": "BTIT14702",
  "semester": 7,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Blockchain Technology",
  "author": "Chandramouli Subramanian, Asha George, Abhilash K.A., Meena Karthikeyan",
  "publisher": "Universities Press",
  "qty": null,
  "amount": 495.0,
  "subject": "Blockchain Technology and Applications",
  "subjectCode": "BTIT14702",
  "semester": 7,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Blockchain: Blueprint for a New Economy",
  "author": "Melanie Swan",
  "publisher": "O'Reilly",
  "qty": null,
  "amount": 599.0,
  "subject": "Blockchain Technology and Applications",
  "subjectCode": "BTIT14702",
  "semester": 7,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Distributed Algorithms",
  "author": "Nancy A. Lynch",
  "publisher": "Elsevier",
  "qty": null,
  "amount": null,
  "subject": "Distributed Systems",
  "subjectCode": "BTIT13702",
  "semester": 7,
  "recBy": "-",
  "dept": "IT"
 },
 {
  "title": "Distributed Computing: Principles and Applications",
  "author": "Liu, M.L.",
  "publisher": "Pearson Education",
  "qty": null,
  "amount": null,
  "subject": "Distributed Systems",
  "subjectCode": "BTIT13702",
  "semester": 7,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Distributed Systems: Concepts and Design",
  "author": "George Coulouris, Jean Dollimore, Tim Kindberg, Gordon Blair",
  "publisher": "Pearson",
  "qty": null,
  "amount": 899.0,
  "subject": "Distributed Systems",
  "subjectCode": "BTIT13702",
  "semester": 7,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Distributed Systems: Principles and Paradigms",
  "author": "Andrew S. Tanenbaum, Maarten Van Steen",
  "publisher": "Pearson",
  "qty": null,
  "amount": 699.0,
  "subject": "Distributed Systems",
  "subjectCode": "BTIT13702",
  "semester": 7,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "21 Internet of Things Experiments",
  "author": "Yashwant Kanetkar",
  "publisher": "BPB Publication",
  "qty": null,
  "amount": 350.0,
  "subject": "IOT and Applications",
  "subjectCode": "BTIT14704",
  "semester": 7,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "An Introduction to Internet of Things: Connecting Devices, Edge Gateway, and Cloud with Applications",
  "author": "Rahul Dubey",
  "publisher": "Cengage India Private Limited",
  "qty": null,
  "amount": null,
  "subject": "IOT and Applications",
  "subjectCode": "BTIT14704",
  "semester": 7,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Getting Started with Raspberry Pi",
  "author": "Matt Richardson, Shawn Wallace, Wolfram Donat",
  "publisher": "Make: Community (ISBN 9781680452464)",
  "qty": null,
  "amount": null,
  "subject": "IOT and Applications",
  "subjectCode": "BTIT14704",
  "semester": 7,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Internet of Things: A Hands-on Approach",
  "author": "Arshdeep Bahga, Vijay Madisetti",
  "publisher": "Universities Press (ISBN 9788173719547)",
  "qty": null,
  "amount": 595.0,
  "subject": "IOT and Applications",
  "subjectCode": "BTIT14704",
  "semester": 7,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Internet of Things: Architecture and Design Principles",
  "author": "Raj Kamal",
  "publisher": "McGraw Hill Education",
  "qty": null,
  "amount": 599.0,
  "subject": "IOT and Applications",
  "subjectCode": "BTIT14704",
  "semester": 7,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Raspberry Pi Cookbook",
  "author": "Simon Monk",
  "publisher": "O'Reilly (ISBN as listed: 7989352133895 — likely a typo/malformed ISBN in source)",
  "qty": null,
  "amount": 699.0,
  "subject": "IOT and Applications",
  "subjectCode": "BTIT14704",
  "semester": 7,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Natural Language Understanding",
  "author": "James Allen",
  "publisher": "Addison-Wesley",
  "qty": null,
  "amount": null,
  "subject": "Natural Language Processing",
  "subjectCode": "BTIT14706",
  "semester": 7,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Speech and Language Processing",
  "author": "Daniel Jurafsky, James H. Martin",
  "publisher": "Pearson Education",
  "qty": null,
  "amount": 899.0,
  "subject": "Natural Language Processing",
  "subjectCode": "BTIT14706",
  "semester": 7,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Computer Security: Principles and Practice",
  "author": "William Stallings",
  "publisher": "Pearson",
  "qty": null,
  "amount": 799.0,
  "subject": "Secure Software Engineering",
  "subjectCode": "BTIT14707",
  "semester": 7,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Secure Software Design",
  "author": "Theodor Richardson, Charles Thies",
  "publisher": "Jones and Bartlett Learning",
  "qty": null,
  "amount": null,
  "subject": "Secure Software Engineering",
  "subjectCode": "BTIT14707",
  "semester": 7,
  "recBy": "-",
  "dept": "IT"
 },
 {
  "title": "Software Engineering – A Practitioner's Approach",
  "author": "Roger S. Pressman",
  "publisher": "Tata McGraw Hill",
  "qty": null,
  "amount": 699.0,
  "subject": "Secure Software Engineering",
  "subjectCode": "BTIT14707",
  "semester": 7,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Software Security: Building Security In",
  "author": "Gary McGraw",
  "publisher": "Addison Wesley Software Security Series",
  "qty": null,
  "amount": null,
  "subject": "Secure Software Engineering",
  "subjectCode": "BTIT14707",
  "semester": 7,
  "recBy": "-",
  "dept": "IT"
 },
 {
  "title": "Software Security: Principles, Policies, and Protection",
  "author": "Mathias Payer",
  "publisher": "Self-published (no publisher listed in syllabus)",
  "qty": null,
  "amount": null,
  "subject": "Secure Software Engineering",
  "subjectCode": "BTIT14707",
  "semester": 7,
  "recBy": "-",
  "dept": "IT"
 },
 {
  "title": "Software Engineering",
  "author": "Rajib Mall",
  "publisher": "PHI",
  "qty": null,
  "amount": 495.0,
  "subject": "Software Testing",
  "subjectCode": "BTIT14703",
  "semester": 7,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Software Testing: A Craftsman's Approach",
  "author": "C.J. Paul",
  "publisher": "CRC Press",
  "qty": null,
  "amount": null,
  "subject": "Software Testing",
  "subjectCode": "BTIT14703",
  "semester": 7,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Software Testing: Principles and Practices",
  "author": "Srinivasan Desikan, Gopalaswamy Ramesh",
  "publisher": "Pearson Education",
  "qty": null,
  "amount": 599.0,
  "subject": "Software Testing",
  "subjectCode": "BTIT14703",
  "semester": 7,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "The Art of Software Testing",
  "author": "G.J. Myers",
  "publisher": "Wiley Interscience",
  "qty": null,
  "amount": 599.0,
  "subject": "Software Testing",
  "subjectCode": "BTIT14703",
  "semester": 7,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Wireless Communication",
  "author": "Theodore S. Rappaport",
  "publisher": "Prentice Hall",
  "qty": null,
  "amount": 699.0,
  "subject": "Wireless Communications",
  "subjectCode": "BTIT14705",
  "semester": 7,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Wireless Communications & Networks",
  "author": "William Stallings",
  "publisher": "Prentice Hall",
  "qty": null,
  "amount": 699.0,
  "subject": "Wireless Communications",
  "subjectCode": "BTIT14705",
  "semester": 7,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Wireless Communications and Networking",
  "author": "Vijay Garg",
  "publisher": "Elsevier",
  "qty": null,
  "amount": null,
  "subject": "Wireless Communications",
  "subjectCode": "BTIT14705",
  "semester": 7,
  "recBy": "Department pick",
  "dept": "IT"
 },
 {
  "title": "Agile Software Development, Principles, Patterns, and Practices",
  "author": "Robert C. Martin, Micah Martin",
  "publisher": "Pearson",
  "qty": 2.0,
  "amount": 11441.0,
  "subject": "Agile Development and UX Design",
  "subjectCode": "",
  "semester": null,
  "recBy": "Dr. Mita Parikh",
  "dept": "IT"
 },
 {
  "title": "Refactoring: Improving the Design of Existing Code",
  "author": "Martin Fowler",
  "publisher": "Addison-Wesley",
  "qty": 3.0,
  "amount": 4850.0,
  "subject": "Agile Development and UX Design",
  "subjectCode": "",
  "semester": null,
  "recBy": "Dr. Mita Parikh",
  "dept": "IT"
 },
 {
  "title": "Business Analytics: Principles, Concepts, and Applications",
  "author": "Marc J. Schniederjans, Dara G. Schniederjans, Christopher M. Starkey Pearson FT Press 2014",
  "publisher": "Pearson",
  "qty": null,
  "amount": 525.0,
  "subject": "Business Anlytics",
  "subjectCode": "",
  "semester": null,
  "recBy": "Snehal Kathale",
  "dept": "IT"
 },
 {
  "title": "CEH Certified Ethical Hacker v13 Study Guide (Sybex Study Guide)",
  "author": "William Panek",
  "publisher": "Sybex Inc",
  "qty": 3.0,
  "amount": 6794.0,
  "subject": "Cyber Security",
  "subjectCode": "",
  "semester": null,
  "recBy": "Prof. Tushar Gohil",
  "dept": "IT"
 },
 {
  "title": "Database Systems: A Practical Approach to Design, Implementation and Management",
  "author": "Thomas Connolly, Carolyn Begg",
  "publisher": "Addison Wesley (Pearson)",
  "qty": 3.0,
  "amount": 2769.0,
  "subject": "Database Management Systems",
  "subjectCode": "",
  "semester": null,
  "recBy": "Prof. Hiren H. Vavaiya",
  "dept": "IT"
 },
 {
  "title": "Designing Data-Intensive Applications: The Big Ideas Behind Reliable, Scalable, and Maintainable Systems, 2nd Edition",
  "author": "Martin Kleppmann (Author), Chris Riccomini (Author)",
  "publisher": "O'Reilly",
  "qty": 3.0,
  "amount": 1950.0,
  "subject": "Database Management Systems",
  "subjectCode": "",
  "semester": null,
  "recBy": "Dr. Mita Parikh",
  "dept": "IT"
 },
 {
  "title": "SQL Queries for Mere Mortals: A Hands-On Guide to Data Manipulation in SQL",
  "author": "John L. Viescas, Michael J. Hernandez",
  "publisher": "Pearson",
  "qty": 3.0,
  "amount": 4613.0,
  "subject": "Database Management Systems",
  "subjectCode": "",
  "semester": null,
  "recBy": "Prof. Hiren H. Vavaiya",
  "dept": "IT"
 },
 {
  "title": "Computer Forensics: Computer Crime Scene Investigation",
  "author": "John Vacca",
  "publisher": "Laxmi Publications",
  "qty": 2.0,
  "amount": 1099.0,
  "subject": "Digital Forensics",
  "subjectCode": "",
  "semester": null,
  "recBy": "Prof. Nitya Komalan",
  "dept": "IT"
 },
 {
  "title": "Digital Forensic: The Fascinating World of Digital Evidences",
  "author": "Dr. Nilakshi Jain and Dr. Dhananjay Kalbande",
  "publisher": "Wiley Press",
  "qty": 2.0,
  "amount": 555.0,
  "subject": "Digital Forensics",
  "subjectCode": "",
  "semester": null,
  "recBy": "Prof. Nitya Komalan",
  "dept": "IT"
 },
 {
  "title": "Practical Digital Forensics",
  "author": "Richard Boddington",
  "publisher": "Packt Publishing",
  "qty": 2.0,
  "amount": 755.0,
  "subject": "Digital Forensics",
  "subjectCode": "",
  "semester": null,
  "recBy": "Prof. Nitya Komalan",
  "dept": "IT"
 },
 {
  "title": "The Basics of Digital Forensics: The Primer for Getting Started in Digital Forensics",
  "author": "John Sammons",
  "publisher": "Syngress",
  "qty": 2.0,
  "amount": 9553.0,
  "subject": "Digital Forensics",
  "subjectCode": "",
  "semester": null,
  "recBy": "Prof. Nitya Komalan",
  "dept": "IT"
 },
 {
  "title": "Distributed Operating Systems: Concepts and Design",
  "author": "Pradeep K. Sinha",
  "publisher": "PHI Learning Pvt. Ltd",
  "qty": 2.0,
  "amount": 1116.0,
  "subject": "Distributed Systems",
  "subjectCode": "",
  "semester": null,
  "recBy": "Dr. Ashish Chaudhari",
  "dept": "IT"
 },
 {
  "title": "Handbook of Natural Language Processing",
  "author": "Nitin Indurkhya, Fred J. Damerau",
  "publisher": "Chapman & Hall/ CRC Press",
  "qty": 3.0,
  "amount": 5124.0,
  "subject": "Natural Language Processing",
  "subjectCode": "",
  "semester": null,
  "recBy": "Dr. Mita Parikh",
  "dept": "IT"
 },
 {
  "title": "Natural Language Processing (2024/25 Edition)",
  "author": "Prof. Sini Raj Pulari",
  "publisher": "Oxford University Press (OUP) India",
  "qty": 3.0,
  "amount": 499.0,
  "subject": "Natural Language Processing",
  "subjectCode": "",
  "semester": null,
  "recBy": "Prof. Bhumika Shah",
  "dept": "IT"
 },
 {
  "title": "Natural Language Processing and Information Retrieval",
  "author": "Tanveer Siddiqui & U.S. Tiwary",
  "publisher": "Oxford University Press (OUP) India",
  "qty": 3.0,
  "amount": 995.0,
  "subject": "Natural Language Processing",
  "subjectCode": "",
  "semester": null,
  "recBy": "Prof. Bhumika Shah",
  "dept": "IT"
 },
 {
  "title": "Practical Natural Language Processing (Greyscale Indian Edition)",
  "author": "Sowmya Vajjala, Bodhisattwa Majumder, Anuj Gupta, Harshit Surana",
  "publisher": "Shroff Publishers / O'Reilly",
  "qty": 3.0,
  "amount": 1900.0,
  "subject": "Natural Language Processing",
  "subjectCode": "",
  "semester": null,
  "recBy": "Prof. Bhumika Shah",
  "dept": "IT"
 },
 {
  "title": "Software Testing: A Craftsman Approach, Fourth Edition",
  "author": "C J Paul",
  "publisher": "CRC Press",
  "qty": 5.0,
  "amount": 3650.0,
  "subject": "Software Testing",
  "subjectCode": "",
  "semester": null,
  "recBy": "Prof. A.B. Mandalaywala",
  "dept": "IT"
 },
 {
  "title": "The Art of Software Testing, 3rd Edition",
  "author": "G J Myers",
  "publisher": "Wiley Interscience",
  "qty": 2.0,
  "amount": 13952.0,
  "subject": "Software Testing",
  "subjectCode": "",
  "semester": null,
  "recBy": "Prof. A.B. Mandalaywala",
  "dept": "IT"
 }
];
